# Generated by Django 3.0.6 on 2020-06-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girodm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='waypoint',
        ),
        migrations.AddField(
            model_name='ride',
            name='code',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='ride_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
