# Generated by Django 3.0.6 on 2020-07-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girodm', '0003_auto_20200701_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pace',
            field=models.CharField(choices=[('ff', 'Family Friendly: slower paced'), ('ep', 'Social (18/21+): casual paced'), ('tp', 'Training Pace: faster paced')], default='ff', max_length=200),
        ),
    ]
