# Generated by Django 3.0.6 on 2020-07-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girodm', '0004_auto_20200701_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='pace',
            field=models.CharField(choices=[('ff', 'Family Friendly'), ('ep', 'Social (18/21+)'), ('tp', 'Training Pace')], default='ff', max_length=200),
        ),
    ]
