# Generated by Django 3.0.6 on 2020-07-05 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('girodm', '0006_ride_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='user',
            new_name='created_by',
        ),
    ]
