# Generated by Django 3.0.6 on 2020-07-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girodm', '0008_auto_20200706_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_type',
            field=models.CharField(choices=[('ff', 'Family Friendly'), ('ep', 'Social (18/21+) Ride'), ('tp', 'Training Ride'), ('sp', 'Special Event')], default='ff', max_length=200),
        ),
    ]
