# Generated by Django 3.0.6 on 2020-06-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=30)),
                ('start_location', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('waypoint', models.CharField(max_length=200)),
                ('end_location', models.CharField(max_length=200)),
                ('end_time', models.DateTimeField()),
                ('private', models.BooleanField(default=False)),
                ('comments', models.CharField(max_length=400)),
                ('pace', models.CharField(choices=[('ff', 'Family Friendly'), ('ep', 'Social (Eighteen +)'), ('tp', 'Training Pace')], default='fam', max_length=200)),
            ],
        ),
    ]
