# Generated by Django 3.0.6 on 2020-07-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girodm', '0010_auto_20200707_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='times_click',
            field=models.IntegerField(default=0),
        ),
    ]
